spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marathon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: hmz990203
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      # 使用了docker网络中的redis地址
      host: 172.18.0.2

server:
  port: 8088

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
