spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marathon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: hmz990203
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8088

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
